version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=crypto-login
      - POSTGRES_USER=crypto-login
      - POSTGRES_PASSWORD=crypto-login
